hydra:
  run:
    dir: .

experiment:
  task: classification
  ckpt_file_name: resnet18_qr_ocqr_calibration_retinamnist

data:
  repo: adience
  num_workers: 4
  batch_size: 128
  pin_memory: true

check_point:
  model_type: resnet
  base: ./assets/checkpoints/qr/
  resnet18_qr: null

uc:
  csv_path: ./assets/uc_results/
  significance_level: 0.1
  methods: [ordinal_cqr]
  num_classes: 8
  class_wise: false
  class_mapping: {"0": 0, "1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7}
  thresholds: [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
  cqr:
    lower_idx: 0
    upper_idx: -1
  
trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  precision: 32

wandb:
  save_dir: ./assets
  entity: gsu-dmlab
  project: uncertainty-medmnist_classification
  offline: false
